steps:
  # Build the Docker image
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

  # # Push the Docker image to Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']

images:
  # Specify the location of the Docker image in Artifact Registry
  - 'gcr.io/$PROJECT_ID/gcpdevops'
