steps:
  # Build the Docker image
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops-dev', '.']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops-dev']
  # Deploy the Docker image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops-dev:latest
      - --location=us-central1
      - --cluster=gcp-devops-project
      - --namespace=gcp-devops-dev
# images:
#   # Specify the location of the Docker image in Artifact Registry
#   - 'gcr.io/$PROJECT_ID/gcpdevops'
